### PR TITLE
Add basestring to 2.7 builtin stubs

### PR DESCRIPTION
**Pull request by kylec1**
Not sure if this is the correct way to represent this.

### CODE REVIEW

**Comment by JukkaL** [comment]
It's definitely better than what we have right now, though not sure if this helps us type check code that uses `basestring`.

**Comment by o11c** [comment]
@JukkaL I think this is correct, since `basestring` does *not* define any of the methods. For new code you should usually use either `AnyStr = TypeVar('AnyStr', unicode, bytes)` (if all arguments/return values should have the same type) or `Union[unicode, bytes]` (if each argument can have a different type).

**Comment by JukkaL** [comment]
I know, but that means that `basestring` isn't very useful in statically typed code. You are right in that you almost always want to use `AnyStr` or `unicode` instead (in Python 2 `str` and `bytes` are subtypes of `unicode`, so no need to use a union type).

**Comment by o11c** [comment]
Ick.

I strongly suggest making implicit conversions between `bytes` and `uncode` a hard error in the type-checker. Otherwise it is impossible to, you know, type-check between them.

**Pull request merged**
