### PR TITLE
Change lib_path: insert MYPYPATH in front; append pwd to end

### PR DESCRIPTION
**Pull request by gvanrossum**
This used to be the opposite.

### CODE REVIEW

**Comment by JukkaL** [comment]
This may have the issue of stubs taking precedence over local files -- I believe that's why the tests are failing. The order of module search path should be something like to preserve compatibility with how things work now (order from highest to lowest priority):

1. MYPYPATH
2. Paths derived from the cwd or target file path
3. Stubs (typeshed)

**Comment by gvanrossum** [comment]
OK, I rearranged some code and the tests should now run (they ran for me locally).

**Comment by gvanrossum** [comment]
(Note, I used commit --amend and push -f, so the PR still looks like one commit -- but I did change it. :-)

**Comment by gvanrossum** [comment]
Fixed by fb09f7d.

**Pull request closed without merging**
