### PR TITLE
New option --python-version.

### PR DESCRIPTION
**Pull request by matthiaskramm**
Store Python version as (major, minor) internally.
This is needed for https://github.com/JukkaL/mypy/issues/882 (and also https://github.com/JukkaL/mypy/issues/874).

### CODE REVIEW

**Comment by o11c** [comment]
I suggest you use `mypy.syntax.dialect.Dialect` from #880 instead. Of course, @JukkaL is inactive so making PRs is kind of pointless.

Instead of only a linear version, it computes the set of actual features, and can create variations. So, you would create one base version (e.g. `Dialect(sys.version[:3])`), and then from that create a version to allow stub-specific syntax in .pyi files but not .py files (currently just `stub_dialect = dialect.add_future('mypy-codec')` to allow annotations). Finally, as each file is parsed, it grows its own sub-dialect depending on the `__future__` statements in effect.

**Comment by matthiaskramm** [comment]
Yes, your work in #880 looks highly relevant. 
I primarily use pyversion to figure out which file to pull in, though. See the work in progress at https://github.com/matthiaskramm/mypy/commit/bdaeea0677e682d9aab14d4b51b6caf20a651885 .
But of course applying the version to parsing is a secondary concern.

**Comment by o11c** [comment]
Note, #887 is cherry-picked from `syntax`, and also updated version to keep the patchlevel, and also support getting `sys.path` etc from an inferior.

**Comment by JukkaL** [comment]
This looks reasonable for now, and unblocks work on typeshed integration. #880 is probably some way off from being merged, it doesn't make sense to wait for that.

**Comment by o11c** [comment]
Note that I really am serious about #887 being ready even though #880 is not. It will almost certainly be needed for #732.

**Pull request merged**
