### PR TITLE
Add `cwd` argument to Python 3 stubs for subprocess calls.

### PR DESCRIPTION
**Pull request by Vlad-Shcherbina**

### CODE REVIEW

**Comment by o11c** [comment]
Maybe you should check *all* the functions in that stub take all the possible keyword arguments.

**Comment by Vlad-Shcherbina** [comment]
I agree that it's totally worth doing eventually. I myself intend to do it, even (no promises though). But I would prefer to do it in a separate PR, unless the owner insists. For now I'm just testing the waters, how contribution to this project works (for instance, whether I'll be asked to send this patch to [typeshed](https://github.com/python/typeshed) instead, or I don't know what).

In addition, I'm reasonably confident in this trivial change, while updating all keyword arguments is much more error-prone, as they are scattered across module documentation.

**Comment by matthiaskramm** [comment]
Yes, sending an (additional?) PR to http://github.com/python/typeshed would make a lot of sense.
(Until https://github.com/JukkaL/mypy/pull/884 is merged, all stubs changes should probably happen in both repositories, to keep things in sync)

**Comment by JukkaL** [comment]
Yeah, until we have a complete stub story sending PRs to typeshed as well would be appreciated (but not necessary). Also, it's totally fine to send only small updates or fixes to stubs such as these.

**Comment by JukkaL** [comment]
And thanks for the PR!

**Comment by matthiaskramm** [comment]
Applied this change to http://github.com/python/typeshed as well.

**Pull request merged**
