### PR TITLE
Fixes for covariance/contravariance + #734

### PR DESCRIPTION
**Pull request by jhance**
We weren't actually propagating variance to the `TypeVarType` correctly.

Fixes this and also #734 which was my end goal when writing this small series.

### CODE REVIEW

**Comment by jhance** [comment]
The implementation for #734 provides test coverage for the first fix so I decided to include these together

**Comment by jhance** [comment]
I have a followup for this that adds checks for inheritance-related variance issues, but because github's model doesn't allow me to submit a PR for commits based on things that aren't in your repository yet, I'll wait until this is merged...

**Comment by o11c** [comment]
If you submit a PR with (all the commits in one PR) + (all the commits in another PR), then if the first PR is merged, they'll disappear frrom the second PR. I've done that with *several* of my PRs, though I have to be careful with rebasing them *all* over the weeks and months that they aren't merged.

**Comment by JukkaL** [comment]
I generally prefer if you can wait until the first PR is merged if you have a second PR on top of that, as things can get very confusing when sending a pull request on top another one that hasn't been merged, especially if the first one requires significant changes based on the review.

**Comment by JukkaL** [comment]
Thanks for the PR, looks good! As mentioned in #734, things like `List[T]` are also problematic, but this brings an incremental benefit so I can merge this.

**Pull request merged**
