### PR TITLE
Include assets in the source tarball.

### PR DESCRIPTION
**Pull request by fladi**
It would be nice to have those files included in the source tarball.

### CODE REVIEW

**Comment by o11c** [comment]
Related: we ought to change travis to run unit tests against an *installed* version of mypy. Probably should switch to setuptools though.

**Comment by JukkaL** [comment]
@fladi Thanks for the PR! Should we also include stubs (everything under `stubs/`)?

@o11c Not sure about that, as at least I almost always run unit tests in a local clone of the repo. However, we should verify that we can run the installed version of mypy.

**Comment by JukkaL** [comment]
Hmm I already forgot what's the purpose of `MANIFEST.in`. It took me a while to figure out the last time because the name isn't very googleable. Anybody have context on this? The commit message should be more explicit about what this is used for.

**Comment by JukkaL** [comment]
Closing as I don't have enough context to review this. Feel free to resend this PR with more context.

**Pull request closed without merging**
