### PR TITLE
Fix #1057

### LINKED ISSUE #1057: %-format checking doesn't understand singleton tuples
A somewhat common pattern is to use `"...%d..." % (var,)` . It's arguably not as useful here as for %s, but I've encountered it in the wild, and it's valid. Mypy complains. Example/comparison:
```
"[%d]" % 42  # OK
"[%d]" % (42,)  # Expected: OK; actually: error
```
The error is:
```
/Users/guido/mypy_tests/mypy_strpol.py:2: error: Incompatible types in string interpolation (expression has type "Tuple[int]", placeholder has type "Union[int, float]")
```

### PR DESCRIPTION
**Pull request by kirbyfan64**
@gvanrossum Does this work?

### CODE REVIEW

**Comment by gvanrossum** [comment]
Yes, this fixes it for me. (Note: `"%s" % ('x',)` probably worked by
accident -- %s takes all argument types.

**Comment by JukkaL** [comment]
Ah, there seems to be a bug -- both the type checker and a unit test apparently caught it :-)

**Comment by kirbyfan64** [comment]
Let's see if it works now... (There's some intense irony in the fact that the type checker failed the type checker.)

**Comment by JukkaL** [comment]
Thanks for the PR! I rebased and pushed the PR (github doesn't recognize that it's in).

**Pull request closed without merging**
