### PR TITLE
readme: separate out the "quick start" so it really is quick

### PR DESCRIPTION
**Pull request by gnprice**

### CODE REVIEW

**Comment by o11c** [comment]
Suggest that this wait until at least #721 is merged and probably #732 as well.

As far as I know, all important environments have `python3`, `pip3`, etc. so we should use that throughout. Also add comments about "yes, mypy runs on python3 even if you are checking python2 code", and once #732 is done remove the comment about python2 mode being unusable.

Also, since the packaged version is so old, we should probably use a git URL, such as what I put in [my requirements.txt here](https://github.com/o11c/lr-parsers/blob/master/requirements.txt), though likely we should include a `@master` for completeness.

**Comment by o11c** [comment]
Actually, should use `python3 -m pip` to be sure the version matches.

**Comment by kirbyfan64** [comment]
@o11c IMO, if the person has multiple Python 3 versions installed, they already know how to invoke `pip`.

**Comment by o11c** [comment]
IME, it's not intuitive that `pip3.2 install --upgrade pip` (which pip spams you until you do) will result in changing `pip` and `pip3` to be 3.2 instead of the newest version.

**Comment by kirbyfan64** [comment]
> IME

"In my experience"? Sorry, I'm bad at abbreviations... ;)

Also, I don't really get what you're saying...I mean, what does that have to do with *running* pip?

**Comment by o11c** [comment]
> "In my experience"? Sorry, I'm bad at abbreviations... ;)

Yes.

> Also, I don't really get what you're saying...I mean, what does that have to do with running pip?

It is quite likely that a user, in the course using `pip`, will unwittingly end up such that `pip3 install mypy-lang` followed by `python3 <something that needs mypy or typing>` will fail with `ImportError`s (or worse, silently use the wrong module, leading to strange errors (or lack of expected errors) later on). Whereas `python3 -m pip install mypy-lang` will always work and DTRT.

**Comment by JukkaL** [comment]
Hmm maybe `pip3` should be the default thing to recommend. Anybody care to check how things are on major platforms (OS X, Windows, Ubuntu 14.04 and newer) when using Python 3? On OS X we should probably consider both the official package from python.org and Homebew.

Here's one data point: On Ubuntu 14.04 `pip` is the Python 2 version. `pip3` is available in the optional package `python3-pip`. Of course, when using virtualenv with Python 3.x `pip` will be the Python 3 version.

**Comment by o11c** [comment]
virtualenv always does pip -> pip3 -> pip3.X symlinks (or copies) though.

**Comment by JukkaL** [comment]
I've decided to recommend `pip3` first. Still not 100% sure about this and we can iterate on this once we get more data.

**Pull request merged**
