### PR TITLE
Load sources while detecting coding according to PEP-263 and should fix #709.

### LINKED ISSUE #709: stubgen UnicodeDecodeError on files containing `coding` magic comment and extended characters
On this file:

https://github.com/dateutil/dateutil/blob/master/dateutil/parser.py

I get: 

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdf in position 1313: invalid continuation byte`

I'm not sure of the best way forward on fixing this issue.

### PR DESCRIPTION
**Pull request by darjus**
And tested against dateutil itself.

### CODE REVIEW

**Comment by JukkaL** [comment]
Thanks for the PR! It seems that this got broken at one point.

I have a few comments:

* `mypy/lex.py` already has encoding detection logic in `find_encoding`. Maybe we could reuse that?
* Python only recognizes encodings in comments. The PR also accepts them in docstrings. `find_encoding` already implements that, so reusing it would fix this :-)
* In Python 2 the default encoding is `ascii`, not `utf-8`. Again `find_encoding` has this sorted.

**Comment by darjus** [comment]
Hey Jukka,

Thanks for feedback. Will take a look and submit new PR when I'm back from vacations :-)

**Comment by JukkaL** [comment]
Okay! I might look into this myself as some my own stuff seems to be breaking because of this. If I do this I'll use your PR as a starting point / inspiration and write a comment here before I start working on it to avoid duplicate work.

**Comment by darjus** [comment]
Hey Jukka,

Please take a look at the new version and let me know what you think? Also added a test for UTF8-BOM

**Comment by JukkaL** [comment]
Looks good now! Thanks for the update!

**Pull request merged**
