### PR TITLE
Get rid of lib-typing and lib-python.

### PR DESCRIPTION
**Pull request by gvanrossum**
I don't think they serve a purpose any more.

### CODE REVIEW

**Comment by gvanrossum** [comment]
(Well, maybe now typing.py needs to be somehow installed.)

**Comment by gvanrossum** [comment]
So, clearly there were more daemons here than I expected... Questions for Jukka:

- What is lib-python for? It seems to be used only by some tests. What does it test?
- What are the python*eval tests for? Were these from when mypy was also a Python runner? Or do they still serve a purpose?

**Comment by JukkaL** [comment]
Getting rid of `lib-typing` is reasonable but we need to install `typing` using some other means if not using Python 3.5.

Regarding your other questions:

* `lib-python` is for regression testing. It has a bunch of manually annotated Python standard library modules that we type check as part of the travis build. I think that it's still somewhat useful, though it doesn't find new issues very often because our unit tests have pretty good coverage. It can find crashes, spurious errors and problems with stubs.
* `python*eval` tests are integration tests. Each test first runs mypy in a subprocess *using the typeshed stubs* and finally runs the test program in a subprocess and verifies the output. They are still useful, though we should figure out a way to make them run faster.

**Comment by gvanrossum** [comment]
OK, I'll restore lib-python and the *eval tests.

I almost solved the typing install problem, except for lib-python -- I'll
figure out a way there too.

**Comment by gvanrossum** [comment]
I'm abandoning this.

**Pull request closed without merging**
