### PR TITLE
Require typing in test-requirements.txt

### PR DESCRIPTION
**Pull request by gnprice**

### CODE REVIEW

**Comment by o11c** [comment]
Mypy depends on its own local fork of typing, it does not work with python3.5's version yet.

**Comment by o11c** [comment]
Also we need to be able to say "use these requirements only if python < 3.5" (the infrastructure will be useful for enum too once we use that)

**Comment by o11c** [comment]
Also the `typing` package on pypi isn't available for 2.7, but mypy's is.

**Comment by kirbyfan64** [comment]
@gnprice 

```bash
PYTHONPATH=`pwd`/lib-typing/3.2:`pwd` python3 tests.py
```

**Comment by gnprice** [comment]
@kirbyfan64 thanks, that works!

I'd love to adjust things so that the README gives instructions that will work totally smoothly. That particular command line, with PYTHONPATH, looks kind of messy and ideally I'd like to find something cleaner than that.

Looking at the Travis build instructions (in `.travis.yml`), it looks like another solution is to do `python3 setup.py install` before attempting the tests. So we could add a line to the running-tests section of the README saying to do that.

@o11c , @JukkaL , is that how you'd run tests in a fresh environment, or would you recommend something else?

**Comment by o11c** [comment]
@gnprice Everything about running the tests is about to change in #721 anyway.

**Comment by JukkaL** [comment]
We can probably wait until we have the new test driver in. Alternatively, maybe we should tweak `sys.path` in `tests.py` to include `lib-typing/3.2`? This way it would be less likely that people would accidentally use an incompatible version of `typing`.

@o11c, does the new test driver set up the environment correctly so that there is no need to tweak `PYTHONPATH` or install anything (other than `test-requirements.txt`)?

**Comment by o11c** [comment]
Yes, since `tests.py` no longer exists, `travis.py` contains the `*PATH`-setting logic that used to be in `travis.sh`. It even uses an `if False` branch to so that code can be typechecked before the `typing` module is actually `import`able.

**Comment by o11c** [comment]
It actually sets it to `lib-typing/3.5:lib-typing/3.4:...:lib-typing/3.0` but stripping out directories that don't exist (so that the newest existing version would be used, though GvR's plan (at least for stubs) is to instead use `if sys.version` checks inside the module instead), and even has logic for 2.7 though that doesn't currently do anything, and probably won't be used with how I now intend to fix #732 and there are likely to be other changes with #884 and #887

**Comment by JukkaL** [comment]
Now we have a new test runner written by @o11c (`runtests.py`, renamed from `travis.py`) that can set up the path correctly for `typing`. Not sure what it does with Python 3.5 (haven't tried it yet) but I think that we can close this PR.

@gnprice Let me know if you still think that this is relevant. The longer-term goal would to migrate mypy to use `typing` installed using `pip`, probably.

**Comment by gnprice** [comment]
The instructions in the README WFM now out of the box. Thanks!

**Pull request closed without merging**
