### PR TITLE
Isinstance for if expressions

### PR DESCRIPTION
**Pull request by jhance**
#806

### CODE REVIEW

**Comment by o11c** [comment]
What about `isinstance(obj, A) and isinstance(obj2, B)` ?

**Comment by jhance** [comment]
See comment in `find_isinstance_check` in `checker.py`). Its not supported by if-statements as far as I'm aware, so I'm not supporting it for if-expressions.

Adding this would require modifying `find_isinstance_check` to be smarter and also returning a `Dict[Node, Tuple[Type, Type]]` or so.

**Comment by JukkaL** [comment]
Yeah, multiple `insinstance` checks is a separate issue (I added #900 for it).

**Comment by JukkaL** [comment]
Looks good, thanks for the PR!

**Pull request merged**
