### PR TITLE
Add line number to "__init__ must return None" error

### PR DESCRIPTION
**Pull request by ddfisher**
This is only a problem in Python 2, so it wasn't caught by the unit tests.  This PR associates the line number with the type when parsing.

### CODE REVIEW

**Comment by gvanrossum** [comment]
Well, there *are* parsing tests for PY2 in  parse-python2.test. Can you add one for this?

**Comment by gvanrossum** [comment]
FWIW I cannot repro this. I have
```
from typing import *

class C:
    def __init__(self, a: int) -> int:
        pass
```
and I correctly get the error for line 4, even when using `mypy --py2`.
```
/Users/guido/mypy_tests/init.py: note: In member "__init__" of class "C":
/Users/guido/mypy_tests/init.py:4: error: The return type of "__init__" must be None
```
Maybe I misunderstand what problem you're solving?

**Comment by ddfisher** [comment]
You understood correctly, but the problem only occurs with Python 2 type annotations.  Try this:
```python
from typing import *

class C:
    def __init__(self, a):
        # type: (int) -> int
        pass
```

I'm a bit surprised that mypy accepts Python 3 type annotations when run in `--py2` mode.

**Comment by ddfisher** [comment]
I tried adding a test to `parse-python2.test`, but unfortunately the distinction isn't captured in the parser test output.

**Comment by gvanrossum** [comment]
Oh, I get it. It's not specific to the `--py2` flag, it's specific to the
`# type: (argtypes) -> rtype` notation. (And now I can repro.)

It's intentional that that's also supported in PY3 code -- that's needed to
support straddling code.

**Comment by gvanrossum** [comment]
A test case for this: add the following to the end of check-basic.test:
```
[case testInitReturnTypeError]
class C:
    def __init__(self):
        # type: () -> int
        pass
[out]
main: note: In member "__init__" of class "C":
main:2: error: The return type of "__init__" must be None
```

**Comment by ddfisher** [comment]
Added.  I didn't realize you could use that syntax without the `--py2` flag.

**Pull request merged**
