### PR TITLE
Add a few more special cases to try_infer_partial_type()

### PR DESCRIPTION
**Pull request by gvanrossum**
Namely: set.discard, list.extend, {set,dict}.update.

It's getting a little ugly -- not sure how best to refactor this.

### CODE REVIEW

**Comment by gvanrossum** [comment]
I'll look into the failure soon. What bugs me most is that the argument type for extend() and update() is more like Iterable. How to extract the item type in that case?

**Comment by gvanrossum** [comment]
Fixed the test, generalized both forms (append etc. and extend etc.). Fingers crossed!

**Comment by gvanrossum** [comment]
Yay! Please review again.

**Comment by JukkaL** [comment]
Looks good! Thanks for the PR!

**Pull request merged**
