### PR TITLE
Fix for issue #615 ( overload resolution for **kwargs)

### PR DESCRIPTION
**Pull request by msoedov**
I not sure if it's the best way to fix this bug but it works just fine.

### CODE REVIEW

**Comment by JukkaL** [comment]
Thanks for the PR! I'm currently at PyCon -- I'll review it when I get back home.

**Comment by spkersten** [comment]
Now, this passes type checking, while I think that it shouldn't:

```python
import typing
class A:
    def f(self, **kw) -> None: pass

class B(A):
    def f(self, y, **kw) -> None: pass
```

**Comment by msoedov** [comment]
@spkersten I don't strongly disagree with you but in general case it should pass type checking when we have smth like this:

```python
import typing

class A:
     def f(self, x=None, y=None) -> None: pass

class B(A):
    def f(self, **kw) ->  None: pass

class C(B):
    def f(self, y, **kw) -> None: pass

```

**Comment by spkersten** [comment]
I don't understand how adding a superclass to `B` in your example (compared to mine) makes a difference. Can you elaborate? Maybe I'm misunderstanding gradual typing (wouldn't be the first time :smile:).

The reason I think this should not pass type checking is the following. For `C` to be a proper subclass of `B`, you should be able to use an instance of `C` in any place where an instance of `B` is expected ([Liskov substitution principle](http://en.wikipedia.org/wiki/Liskov_substitution_principle)). For example in this case:

```python
def g(b: B):
    b.f()

c = C()
g(c)
```

However, this would fail in your example, because the function being called is `C.f` which expects (after the implicit `self`) a second argument.

**Comment by msoedov** [comment]
You are right, I'll fix it soon

**Comment by JukkaL** [comment]
Actually, I'm no longer sure if #615 is an actual bug... Class `B` in the issue is not compatible with `A` since `B.f` accepts no positional arguments, which is incompatible with `A.f`. Maybe we shouldn't allow this code after all.

However, if there are no type annotations, we should just accept everything, in the spirit of gradual typing. When both the original method and the override have annotations, we should type check method signature compatibility properly (Liskov substitution principle etc.). However, mypy is not too picky and doesn't check that argument names are compatible, since these would cause a lot of existing code to generate false positives.

**Comment by JukkaL** [comment]
I think that #615 is actually not correct. However, this could still be improved, in case there are keyword-only arguments. So this should be valid, but the original examples should be rejected (as they change the supported positional arguments, which is not strictly okay):

```python
import typing

class A:
     def f(self, *, x=None, y=None) -> None: pass

class B(A):
    def f(self, **kw) ->  None: pass

class C(B):
    def f(self, *, y, **kw) -> None: pass
```

@msoedov Are you willing to modify your PR to only apply to cases such as above, where we only target keyword-only args and `**kwargs`?

**Comment by JukkaL** [comment]
And apologies for having been very unresponsive!

**Comment by JukkaL** [comment]
Closing as there hasn't been activity in a long time and I don't have time to work on this now.

**Pull request closed without merging**
