### PR TITLE
Fix #996

### LINKED ISSUE #996: Incorrect number of type arguments causes internal error
```
from typing import TypeVar

T = TypeVar('T')

class C(object):  # forgot to add type params here
    def __init__(self, t : T) -> None:
        self.t   = t

c = C(t = 3)  # type: C[int]  # this will crash
```

causes:

```
Traceback (most recent call last):
    ...
    cb = infer_constraints(mapped.args[i], instance.args[i],
IndexError: list index out of range
```

I guess this generalizes #981 and provides an additional example, here with an (accidentally) non-generic type (though the same happens if too few type arguments are supplied).  I'm not sure if it overlaps with #300.

### PR DESCRIPTION
**Pull request by kirbyfan64**
@bcdarwin @gvanrossum Please try and let me know if it works!

### CODE REVIEW

**Comment by gvanrossum** [comment]
Sadly doesn't look like it fixes #991 for me. So maybe the two issues are not the same.

**Comment by bcdarwin** [comment]
This doesn't seem to crash any more, although it's still possible to omit the type arguments entirely (i.e., annotate a variable with type `C` rather than `C[int]`) and silently pass the checker -- not sure that's intended.

**Comment by JukkaL** [comment]
Ah, a test case seems broken. Anyway, this will fix the crash but there could be other similar issues that this won't catch :-(

I believe that the root cause of the crash is that recently I changed mypy to type check code even if there are semantic errors. However, the type checker assumes certain invariants to hold after semantic analysis, such as the number of type arguments being correct, and this no longer is necessarily the case.

I'm thinking about a more general fix where we replace bad types with `Any` or something during semantic analysis, so that the type checker can still assume that things are correct. This would make the type checker simpler (actually no more complex than it is right now).

**Comment by JukkaL** [comment]
I pushed a hopefully more general fix to this issue, so I'm closing this PR.  @kirbyfan64 thanks for the original PR!

**Pull request closed without merging**
