### PR TITLE
Fix/Improve Test Driver

### PR DESCRIPTION
**Pull request by o11c**
The current `travis.sh` is broken in a number of ways. This fixes most of them.

Note: there are legitimate bugs exposed in mypy here, that's why the tests fail. The stubs do *not* appear to be incorrect.

### CODE REVIEW

**Comment by o11c** [comment]
Okay, I've refactored so that this can be merged before the XML one.

**Comment by o11c** [comment]
@JukkaL I'm really not sure if I can solve the bug this exposes. I just investigated my hypothesis and it turned out to be fruitless.

(An example of) The failing test is:
`mypy -c 'import requests.packages.urllib3.connection'`

Which is curious because this works and *does* result in an import of the `connection` module:
`mypy -c 'import requests.packages.urllib3'`

But this doesn't work:
`mypy -c 'import requests.packages.urllib3, requests.packages.urllib3.connection'`

This changes the error message:
`mypy -c 'import requests.packages.urllib3.connectionpool, requests.packages.urllib3.connection'`

And this somehow works:
`mypy -c 'import requests.adapters, requests.packages.urllib3.connectionpool, requests.packages.urllib3.connection'`


So all I can really say is that this is some subtle ordering problem that is beyond my skill/knowledge.

**Comment by o11c** [comment]
I added a list of XFAILs so at least we can get meaningful test results until the real bug is fixed.

Also managed to find a non-racy way to run tasks in parallel without `os.waitid`.

Getting a funny "cannot find builtins" failure now though ...

**Comment by JukkaL** [comment]
Thanks for the PR! This is pretty big so it might take a while but I hope to have time to review it this weekend.

**Comment by o11c** [comment]
Ugh, your recent pushes made there be conflicts.

**Comment by JukkaL** [comment]
I've now merged your changes to the current master (haven't pushed them yet) and have been playing around with them a little. It's much better to run tests in parallel, type check all stubs and  to have automatic test discovery!

There are some regressions that shouldn't be difficult to fix or work around:

* Running individual test cases requires more work than before (`python3 -m mypy.munit -m mypy.test.testfoo "*foobar*"` vs `python3 tests.py "*check*foobar*"`). It's probably worth figuring a simpler way of running a subset of unit tests.

* The output is way noisier than before. I don't want many pagefuls of output if things go right. By default, it should not output a lot of stuff (but it's okay to write more verbose output to a log file so that it's possible to debug if things go wrong).

* If `travis.py` is the only entry point to running multiple test suites, we should probably rename it to something else as people will also want to run it locally (`tests.py`?).

* Previously there was an easy way to run only inexpensive (unit) tests (`tests.py`). It would be nice to be still able to easily skip expensive integration tests but run everything else (at least pythoneval, which is really slow). Or maybe we could run python eval tests in parallel by splitting it into multiple chunks.

**Comment by o11c** [comment]
> Running individual test cases requires more work than before (python3 -m mypy.munit -m mypy.test.testfoo "*foobar*" vs python3 tests.py "*check*foobar*"). It's probably worth figuring a simpler way of running a subset of unit tests.

`mypy.myunit` is not intended to be run by hand at the moment (this may change if we switch from distutils to setuptools and get easy `entry_point` management.

What I usually do is run `./travis.py patterns...`. For example, I have my vim configured to run `./travis.py mypy.syntax` to only run syntax-related tests. This has the advantage of *also* running the type-checker for those modules, not just the unit test modules.

If it's really worth running just a single unit test (since other than pythoneval, test modules are fast), I briefly experimented with `./travis.py modulepatterns... -- arguments` but stopped since it wasn't clear what should happen if there was more than one module. Perhaps `./travis.py modulepattern:argument`?

Really, `mypy.myunit` needs more love; it is currently a half-assed approach to testing. Of particular relevance to this issue, it ought to have discovery of its own. I have been thinking about switching to layout compatible with `py.test` however.

> The output is way noisier than before.

Am I the only one who always runs test drivers in verbose mode? It's not like there is anything valuable in the terminal's scrollback, and the failures are nicely collected at the end. But I'm certainly not opposed to adding command-line options to travis.py to control it.

I prefer immediate output because deferred output and log files can be problematic, though I admit that I am used to working in C and C++ where memory corruption and sudden exit are more common (though they're certainly possible in python also).

> If travis.py is the only entry point to running multiple test suites, we should probably rename it to something else as people will also want to run it locally (tests.py?).

I deliberately did not name it `tests.py` because it is not at all similar to the `tests.py` that existed before this patch. And I think people should draw comfort in knowing that the way they are running tests matches the way tests will be run automatically.

Bikeshed alternative: `runtests.py` ?

> Previously there was an easy way to run only inexpensive (unit) tests

Currently, `./travis.py unit-test` is my preferred way to run all unit tests, which includes pythoneval tests. Perhaps the collector should be given additional knowledge about the pythoneval tests specifically (some form of this may be needed anyway for #732), or possibly you could add negative patterns as well as positive patterns.

***

This PR is not an attempt to provide perfection, only an improvement. Ideally I think `mypy.myunit` would integrate all the abilities of travis.py and `mypy.waiter` but I don't have a clear design yet and I intend to work on other things first.

**Comment by o11c** [comment]
@JukkaL Can you please (rebase and) merge this? I have no clue what is acceptable to you, and you keep on giving painful delays.

I'm almost done with the new parser (still need to finish expression parsing and port billions of unit tests), but for lowering I really need to be able to use the updated version of mypy.

**Comment by JukkaL** [comment]
@o11c: Sorry for having being unresponsive; I've been out of the country for almost 3 weeks now and been very busy. Things will calm down next week. I may have a few hours later this week, but I can't promise anything.

**Comment by o11c** [comment]
Note, there is a rebased version of this at https://github.com/o11c/mypy/tree/driver-rebased but I haven't investigated the new test failures yet.

**Comment by o11c** [comment]
Okay, fixed.

**Comment by o11c** [comment]
Okay, fixed. More cyclic import problems that probably *should* be fixed elsewhere, but ... explicit annotations will do for now.

**Comment by o11c** [comment]
Rebased to fix another bug caused by upstream changes, and made the linter stop complaining.

I really think the linter is being stupid for some of those things though.

**Comment by o11c** [comment]
@JukkaL note that I still have to xfail 4 of the stubs, even though they are correct. Obviously there's still a cyclic import problem somewhere.

**Comment by matthiaskramm** [comment]
I pushed a typeshed version of this branch, called "driver+typeshed".

**Comment by o11c** [comment]
Okay, I added `-v` and `-q` options to control the verbosity. Also implemented `-x` for negative patterns.

* With `-q -q`, you get no output except the summary.
* With `-q`, you get a series of dots for every passed suite and a letter for failures.
* By default, you get a constantly-updating status line. This sometimes interferes with output from the inferiors - they should be taught not to produce output except for errors, and error output is usually long enough that it's fine. Still, it's overall a good choice.
* With `-v`, you get START/EXIT/SIG for every job as it occurs. I have enabled this on Travis.
* With `-v -v`, you get SELECT output at startup
* With `-v -v -v`, you get OMIT output at startup

I really hadn't wanted to do anything this fancy at this stage - myunit ought to become a real test framework before we care about the driver's output (it should use a TAP-like protocol to talk to *intelligent* inferiors that run named tests, instead of oblivious subprocesses). But with nearly 3 months unmerged, this PR can no longer afford to be only "fix the horribly broken stuff"

**Comment by JukkaL** [comment]
I played around with the most recent revision. This is much improved. I like the default level of output (other than the issues I mention below). 

These need to fixed before I can merge this:

* I really need a way to run individual unit tests easily. My typical workflow is strongly based on running a few unit tests repeatedly and only once they pass running the entire suite. This way I can use debug prints in code to debug test failures easily. If I run many tests with debug prints the output has so much volume that it's useless. Something like `./runtests.py checker:test_case_name` would be okay.
* It's probably best to stop using `tests.py` as the name, but `travis.py` is not good either. `runtests.py` sounds okay to me.
* `README.md` should describe how to run tests (both the entire suite and individual unit tests).
* The outputs of XFAIL tasks should be supressed in the default mode, as they look like test failures but nothing actually needs to be done about them.
* I got some failures when I ran it:

  ```
 FAILURE check libpython (3.2) module test.test_set
 FAILURE check libpython (3.2) module test.test_pprint
 FAILURE check libpython (3.2) module test.test_getopt
 FAILURE check libpython (3.2) module test.test_fnmatch
 FAILURE check libpython (3.2) module test.test_posixpath
 FAILURE check libpython (3.2) module test.test_random
 FAILURE check libpython (3.2) module test.test_glob
 FAILURE check libpython (3.2) module test.test_shutil
 FAILURE check libpython (3.2) module test.test_tempfile
 FAILURE check libpython (3.2) module test.test_genericpath
 FAILURE check libpython (3.2) module test.test_base64
 FAILURE check libpython (3.2) module test.test_textwrap
 FAILURE check libpython (3.2) module test.test_subprocess
```

Feature ideas (it's not essential to implement all of these for now; in no particular order):

1)

`runtests.py -h` should provide better help and describe what each of the arguments means.

2)

There should be better mapping between task failure and where things went wrong. In particular, if a task fails, there should always be a pointer to a file which contains the implementation of the failed test/task. For example, if `libpython ...` fails, the starting point for looking for what went wrong is in `add_libpython` in `travis.py`, but I can't find that without grepping for `libpython` within the code base. As a rule, it shouldn't be necessary to grep for things to figure out what actually failed. The previous CI script was sufficiently simple that you could just browse it to see what was going on, but the new runner is sufficiently complex that more context would be useful.

3)

The outputs of tasks should be serialized, and there should be a title showing the name of the associated task for each output. It's important for usability to have consistent output. It would be nice to split output of each task chunked at a test case boundarye (instead of arbitrarily interleaved), so that we could get more incremental output, but just buffering until a task has finished and printing out the output is also okay. Having outputs from multiple tasks interleaved can make it difficult to figure what is going on. For example, I got stack traces which gave no indication to which task was failing:

```
Traceback (most recent call last): running {#216, #419, #420, #421, #422, #435, #436, #437}
  File "/home/jukka/project/mypy/scripts/mypy", line 4, in <module>
    from mypy.main import main
  File "/home/jukka/project/mypy/mypy/main.py", line 6, in <module>
    import subprocess
  File "/home/jukka/project/mypy/lib-python/3.2/subprocess.py", line 413, in <module>
    _create_pipe = _posixsubprocess.cloexec_pipe
AttributeError: 'module' object has no attribute 'cloexec_pipe'
```

4)

There should be a total number of test cases shown in the summary, similar to the previous runner. We can either count each task as a single test case by default (if it doesn't include a test suite to be run), or we can count tasks and tests separately. The motivation here is threefold. First, showing the number of test cases may motivate people to add more tests, as there is a clearly visible impact in the stat. Second, it gives more visibility to the usefulness of the test suite (assuming that having more tests generally is better than fewer tests). Third, if somebody accidentally disables a large set of test cases, it's easier to spot this issue.

5)

The output should in general be formatted more nicely with empty lines separating sections. For example, if I get a test failure the output currently looks like this:

```
PARALLEL 8
SUMMARY  21 tasks selected
Expected: failed 0, pending 10; running {#0, #2, #3, #5, #6, #8, #9, #10}       
  xfile: note: In function "f":                 (diff)
  file:1: error: Parse error before end of line
  file: note: At top level:
  file:2: error: Inconsistent indentation
Actual:
  file: note: In function "f":                  (diff)
  file:1: error: Parse error before end of line
  file: note: At top level:
  file:2: error: Inconsistent indentation

Alignment of first line difference:
  E: xfile: note: In function "f":
  A: file: note: In function "f":
     ^
Traceback (most recent call last):
  File "/home/jukka/project/mypy/mypy/test/data.py", line 137, in run
    self.perform(self)
  File "/home/jukka/project/mypy/mypy/test/testparse.py", line 74, in test_parse_error
    testcase.line))
  File "/home/jukka/project/mypy/mypy/test/helpers.py", line 84, in assert_string_arrays_equal
    raise AssertionFailure(msg)
AssertionFailure: Invalid compiler output (mypy/test/data/parse-errors.test, line 11)

test_testparse_ParseErrorSuite.testInvalidFunction failed

1/286 test cases failed.ing 8; running {#0, #2, #3, #6, #9, #10, #11, #12}      
*** FAILURE ***
SUMMARY  1/21 tasks failed                               
 FAILURE run unit-test mypy.test.testparse
SUMMARY  1/21 tasks failed
```

Related things are not grouped at all in the output and it's difficult to parse for humans. 

It would be better if it looked something like this (this includes some other ideas as well in addition to grouping):

```
PARALLEL: 8
SUMMARY: 21 tasks selected

ERROR: run unit-test mypy.test.testparse:

Expected:
  xfile: note: In function "f":                 (diff)
  file:1: error: Parse error before end of line
  file: note: At top level:
  file:2: error: Inconsistent indentation
Actual:
  file: note: In function "f":                  (diff)
  file:1: error: Parse error before end of line
  file: note: At top level:
  file:2: error: Inconsistent indentation

Alignment of first line difference:
  E: xfile: note: In function "f":
  A: file: note: In function "f":
     ^
Traceback (most recent call last):
  File "/home/jukka/project/mypy/mypy/test/data.py", line 137, in run
    self.perform(self)
  File "/home/jukka/project/mypy/mypy/test/testparse.py", line 74, in test_parse_error
    testcase.line))
  File "/home/jukka/project/mypy/mypy/test/helpers.py", line 84, in assert_string_arrays_equal
    raise AssertionFailure(msg)
AssertionFailure: Invalid compiler output (mypy/test/data/parse-errors.test, line 11)

test_testparse_ParseErrorSuite.testInvalidFunction failed

SUMMARY:
    ERROR: run unit-test mypy.test.testparse
        test_testparse_ParseErrorSuite.testInvalidFunction failed

*** 1 failed, 306 passed in 2.334 seconds ***
```

6) 

What happens if a task gets stuck? We should have a timeout and if that happens, display any buffered output from the task. The timeout could be something like 2 minutes.

7)

Currently the python evaluation test cases tend to be run last, and this slows down test execution as during the final part of execution only one task is running. It would be more efficient to start long-running tasks early on.

8)

On passing there should be no output other than a summary of what was run, as you suggested. We should show any stdout output from tasks, however, to make it easier to debug things, so we should just run tasks in silent mode. We need to figure out how to propagate information about passed tasks back to the runner. We could either have magic output that gets stripped and consumed by the runner or we could generate temp files with information about things like the number of test cases run.

**Comment by o11c** [comment]
Ignore the Travis failure right now, it is because I have to write a stubs for the `pipes` module still. Will rebase again in a bit.

> These need to fixed before I can merge this:

All done, except the XFAIL one, which I strongly disagree with.

> * I really need a way to run individual unit tests easily. My typical workflow is strongly based on running a few unit tests repeatedly and only once they pass running the entire suite. This way I can use debug prints in code to debug test failures easily. If I run many tests with debug prints the output has so much volume that it's useless. Something like ./runtests.py checker:test_case_name would be okay.

Before, you could do `python3 -m mypy.myunit -m mypy.test.testfoo '*foo*'`. Now I've added `./runtests.py 'testfoo' -a '*foo'`, as well as a legacy wrapper script (will likely go away once with setup.py changes). I had to do a little extra work to make sure that `./runtests.py -a -v` passed `-v` to the inferior rather than parsing it itself.

That said, whenever I'm working on tests in one file, I usually want to run all the other tests in the same file to make sure I haven't accidentally broken anything, and it's usually fast enough.

> * It's probably best to stop using tests.py as the name, but travis.py is not good either. runtests.py sounds okay to me.

Done.

> * README.md should describe how to run tests (both the entire suite and individual unit tests).

Done.

> * The outputs of XFAIL tasks should be supressed in the default mode, as they look like test failures but nothing actually needs to be done about them.

Disagree strongly. Anything XFAIL should be a very high priority, the only reason I implemented that output level was because I don't have the knowledge to fix them properly.

For usual development you're usually passing either inclusive or exclusive filters so you won't see them anyway.

> * I got some failures when I ran it:
> 
>     FAILURE check libpython (3.2) module test.test_<snip>

This is caused by a buggy `PYTHONPATH` value in the environment, containing a relative path (which includes `.` and the empty string). I've added logic to bail out if that is detected.

Note in particular that setting `PYTHONPATH` to the empty string is *not* the same as having it unset. The correct way to add to a `PATH`-like environment variable is `export PYTHONPATH=${ADD_PYTHONPATH}${PYTHONPATH+:}${PYTHONPATH}`. Do not use `export PYTHONPATH=${ADD_PYTHONPATH}:${PYTHONPATH}` (which adds an empty component) or `export PYTHONPATH=${ADD_PYTHONPATH}${PYTHONPATH:+:}${PYTHONPATH}` (which removes an empty component).

I chose to bail out rather than attempt to fix it because:

* Explicit is better than implicit.
* The bug may affect programs other than mypy.

> Feature ideas (it's not essential to implement all of these for now; in no particular order):

> 1) runtests.py -h should provide better help and describe what each of the arguments means.

Done. We still need a `myargparse` though.

> 7) Currently the python evaluation test cases tend to be run last.

I've moved the `add_myunit` call up a little. But see below.

> other numbers)

Further improvements will require making myunit aware that it is being run as a slave. I imagine that, in the long run, `mypy.waiter` will be absorbed into `myunit`, but it's not yet clear how it will need to change e.g. for #732.

I have some initial thoughts for a [TAP](https://en.wikipedia.org/wiki/Test_Anything_Protocol)-like protocol for recursive tests (TAP itself is too primitive, unfortunately), as well as a [list of annotations and results](https://gist.github.com/o11c/ef8f0886d5967dfebc3d) that ought to be supported.

The most important case is lifting test enumeration and parallelism up to the top level. Besides giving more meaningful counts, this will completely fix the `pythoneval`-related problems by running them in parallel with *each other* instead of only with other test suites.

**Comment by o11c** [comment]
Rebased; also note that I enabled IRC notifications.

**Comment by kirbyfan64** [comment]
> The current `travis.sh` is broken in a number of ways.

Why exactly? I knew I had little clue what I was doing when I wrote it (I had just recently moved from Windows to Linux and was still getting used to Bash stuff), but I didn't realize it was *broken*...

**Comment by o11c** [comment]
@kirbyfan64

>> The current travis.sh is broken in a number of ways.
> 
> Why exactly? I knew I had little clue what I was doing when I wrote it (I had just recently moved from Windows to Linux and was still getting used to Bash stuff), but I didn't realize it was broken...

The biggest issue is that it doesn't actually run all the tests (does not find files recursively, does not check files independently (leading to missing `ImportError`)).

On the other hand, the most *obvious* error is the fact that it won't work at all in environments where `python` is `python2`, which is the typical case outside of a virtualenv (and other parts of mypy, at least at the time, would disable themselves if `python` referred to `python3`).

I *think* those two are the only bugfixes, but there are a *lot* of niceties I also added, some of which could almost be considered bugs because of how commonly their existence is expected.

**Comment by o11c** [comment]
Actually there *is* a third bug: it was only checking 3.2, not 3.3+.

**Comment by o11c** [comment]
@JukkaL obligatory ping

**Comment by o11c** [comment]
Rebased on top of #903 for easier maintenance of my other branches.

But seriously, this is embarrassing.

**Comment by JukkaL** [comment]
@o11c: This PR has taken me a lot of work to review, and because it has sometimes felt like a burden it's also been slow. I've done some reflection and tried to understand why this happened and how we can make this less likely to happen in the future. Here are my thoughts: http://www.mypy-lang.org/wiki/GoodPullRequest

Anyway, I'm going to do another round of review today and hopefully I can finally merge it.

**Pull request merged**
