### PR TITLE
Rudimentary support for Enum

### PR DESCRIPTION
**Pull request by spkersten**
This PR adds rudimentary support for Python 3.4's Enum type. The only thing it does is setting the type of `Color.red` to `Color` given `class Color(Enum): red = 1`.

While it doesn't check much, it suppresses the error that mypy currently reports for the most basic use of `Enum`.

### CODE REVIEW

**Comment by presidento** [comment]
Can you add tests for the new functionality?

**Comment by spkersten** [comment]
@presidento Sure, but I've not time for that now. (I've to figure out how to make a Python 3.4 only test; not sure if that is currently possible.)

Also, the code needs to check that the version of Python is > 3.4.

**Comment by JukkaL** [comment]
Currently Python version only affects `mypy/test/data/pythoneval.test`. You can add Python 3.4 only test cases easily by modifying `python_34_eval_files` in `mypy/test/testpythoneval.py`.

**Comment by o11c** [comment]
IMO instead of making it 3.4 only, it should add a dependency on `enum34` for older versions.

**Comment by JukkaL** [comment]
It would be great to get this PR in! Apologies for the delay -- I've been traveling a lot and moving (twice!) in the last month, but things are now getting back to normal.

@spkersten Can you have a look at the test failure?

**Comment by JukkaL** [comment]
@o11c I created a task for this: https://github.com/JukkaL/mypy/issues/742

**Pull request merged**
